### ISSUE TITLE
[flightgear-git] VR dependencies

### ISSUE THREAD

**Issue by amalon** [acxz/flightgear-arch#1]
As noted here:
https://aur.archlinux.org/packages/flightgear-git#comment-846624

Flightgear next will now make use of osgXR if available to enable some basic VR support, otherwise it will try to build its own static built-in version of osgXR which would implicitly depend on OpenXR.

So 3 possible options (in order of preference):

1) add 'libosgXR' to depends so that the osgXR shared library provided by https://aur.archlinux.org/packages/osgxr/ (which pulls in 'openxr') is automatically used (cmake ENABLE_VR and SYSTEM_OSGXR will both default to ON)

2) add the cmake option -DSYSTEM_OSGXR=OFF and add 'openxr' 'libglvnd' to depends, so flightgear will attempt to build its own static built-in version of osgXR (which would depend on OpenXR (and GLX)).

3) add the cmake option -DENABLE_VR=OFF to prevent the implicit dependencies, but obviously disables any VR support.

My plan is to implement option (1) and get it tested in a clean chroot (once I can figure out getting the dependencies that way). osgXR's API isn't necessarily stable yet (and flightgear is the only real user I think). I already update osgXR's AUR PKGBUILD if needed before updating flightgear next branch.

If a new release of flightgear is made and further API changes are necessary I'll deal with it then, hopefully just requiring a rebuild against the latest osgXR. Worst case one of the packages can be switched to option (2).

**Comment by acxz** [comment]
> tested in a clean chroot (once I can figure out getting the dependencies that way)

For building in a clean chroot, I highly recommend paru's `--chroot` flag. It makes clean chroot'ing quite painless.
