### ISSUE TITLE
[flightgear] 2020.3.19 build error: ‘shared_mutex’ in namespace ‘std’ does not name a type

### ISSUE THREAD

**Issue by alfmel** [acxz/flightgear-arch#11]
When building flightgear version 2020.3.19 on up-to-date Arch Linux system on x84_64, I get the following error:

```
Building CXX object utils/fgelev/CMakeFiles/fgelev.dir/fgelev.cxx.o
In file included from /home/alberto/aur/flightgear/src/flightgear-2020.3.19/utils/fgelev/fgelev.cxx:30:
/usr/include/simgear/props/props.hxx:1403:18: error: ‘shared_mutex’ in namespace ‘std’ does not name a type
 1403 |     mutable std::shared_mutex _mutex;
      |                  ^~~~~~~~~~~~
/usr/include/simgear/props/props.hxx:1403:13: note: ‘std::shared_mutex’ is only available from C++17 onwards
 1403 |     mutable std::shared_mutex _mutex;
      |             ^~~
make[2]: *** [utils/fgelev/CMakeFiles/fgelev.dir/build.make:76: utils/fgelev/CMakeFiles/fgelev.dir/fgelev.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2697: utils/fgelev/CMakeFiles/fgelev.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

Let me know what other information you may need. Thanks in advance!

**Comment by acxz** [comment]
Hello @alfmel can you mention how you are building the package, i.e. with what commands?

**Comment by alfmel** [comment]
> Hello @alfmel can you mention how you are building the package, i.e. with what commands?

At first I was using Aura. I then downloaded the AUR package, extracted it and simply ran `makepkg`. I also replaced my `makepkg.conf` file with the latest `pacsave` version and things still fail.

**Comment by acxz** [comment]
Pushed out a change, that let me finish the build of `flightgear`. Let me know if the newest change fixed this issue for you, as I am not able to reproduce it.

**Comment by alfmel** [comment]
Sorry, it didn't fix the issue. I still get the same error. :disappointed: 

I did notice the problem seems to come from `/usr/include/simgear/props/props.hxx`. I wonder if I have to update my version of simgear. I am on `simgear-git 2020.4.0r6133.8245afcd-1`.

What version of simgear are you using, @acxz ?

**Comment by alfmel** [comment]
I noticed you had updated the `simgear` AUR package recently, and I rebuilt it and reinstalled it, removing my older GIT build. With `simgear-2020.3.19-3` installed, `flightgear-2020.3.19-2` built without any issues. It seems my problem was a simgear and flightgear version mismatch.

Thanks for your help.

**Comment by acxz** [comment]
Glad to hear!
