### ISSUE TITLE
[simgear] error: field ‘_uniforms’ has incomplete type ‘simgear

### ISSUE THREAD

**Issue by WalterSmuts** [acxz/flightgear-arch#6]
```
/home/walter/.cache/yay/simgear/src/simgear-2020.3.13/simgear/scene/viewer/Compositor.hxx:137:34: error: field ‘_uniforms’ has incomplete type ‘simgear::compositor::Compositor::BuiltinUniforms’ {aka ‘std::array<osg::ref_ptr<osg::Uniform>, 14>’}
  137 |     BuiltinUniforms              _uniforms;
      |                                  ^~~~~~~~~
In file included from /usr/include/c++/12.2.1/bits/hashtable_policy.h:34,
                 from /usr/include/c++/12.2.1/bits/hashtable.h:35,
                 from /usr/include/c++/12.2.1/unordered_map:46,
                 from /home/walter/.cache/yay/simgear/src/simgear-2020.3.13/simgear/scene/viewer/Compositor.hxx:20:
```

Getting this for both `flight-gear` and `flight-gear-git`

**Comment by WalterSmuts** [comment]
Seems to be a c++11 vs c++ 17 issue... flightgear and simgear both specify 11 in the `CMakeLists.txt` but seems to only build for me when I change to 17. I wonder how others got this buillt in the first place?

**Comment by hibert23** [comment]
I have exactly the same problem. The error occurs under arch for both packages as well for me, **flight-gear-git** and  **flight-gear**

`[ 95%] Building CXX object simgear/CMakeFiles/SimGearScene.dir/scene/viewer/Compositor.cxx.o
In Datei, eingebunden von /home/hibert/simgear/src/simgear-2020.3.17/simgear/scene/viewer/Compositor.cxx:17:
/home/hibert/simgear/src/simgear-2020.3.17/simgear/scene/viewer/Compositor.hxx:137:34: Fehler: Feld »_uniforms« hat unvollständigen Typen »simgear::compositor::Compositor::BuiltinUniforms« {aka »std::array<osg::ref_ptr<osg::Uniform>, 14>«}
  137 |     BuiltinUniforms              _uniforms;
      |                                  ^~~~~~~~~
In Datei, eingebunden von /usr/include/c++/12.2.1/bits/hashtable_policy.h:34,
                 von /usr/include/c++/12.2.1/bits/hashtable.h:35,
                 von /usr/include/c++/12.2.1/unordered_map:46,
                 von /home/hibert/simgear/src/simgear-2020.3.17/simgear/scene/viewer/Compositor.hxx:20:
/usr/include/c++/12.2.1/tuple:1595:45: Anmerkung: Deklaration von »simgear::compositor::Compositor::BuiltinUniforms« {aka »struct std::array<osg::ref_ptr<osg::Uniform>, 14>«}
 1595 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
make[2]: *** [simgear/CMakeFiles/SimGearScene.dir/build.make:1826: simgear/CMakeFiles/SimGearScene.dir/scene/viewer/Compositor.cxx.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:887: simgear/CMakeFiles/SimGearScene.dir/all] Fehler 2
make: *** [Makefile:156: all] Fehler 2
`

I'm still new to the Linux world. Can you show me what change you made?



> Seems to be a c++11 vs c++ 17 issue... flightgear and simgear both specify 11 in the `CMakeLists.txt` but seems to only build for me when I change to 17. I wonder how others got this buillt in the first place?

unfortunately I can't get any further. Thanks for the help

**Comment by WalterSmuts** [comment]
There's a file called `CMakeLists.txt` that specifies the version. Search for `CMAKE_CXX_STANDARD` and you want to change it from `11`to `17`.

**Comment by WalterSmuts** [comment]
Oh... And I didn't use the AUR package but rather just built from the flightgear repo directly:
https://github.com/FlightGear/flightgear

**Comment by alvarosimon** [comment]
Same issue here, this should be fixed in `PKGBUILD` and set `CMAKE_CXX_STANDARD`

**Comment by alvarosimon** [comment]
I have tried with `*-git` AUR packages and it works without issues. I didn't change anything, just removed old `flightgear` , `flightgear-data` and `simgear` and reinstall `-git` AUR versions.

**Comment by hibert23** [comment]
> Oh... And I didn't use the AUR package but rather just built from the flightgear repo directly: https://github.com/FlightGear/flightgear

Sry for my late reply on your post, I was on vacation. Building fg directly from the flightgear github repository works here without any change in CMakeLists.txt. Thx for your great help anyway.
